# Generated by Django 3.2.7 on 2021-10-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_project', models.CharField(max_length=255, verbose_name='Project name')),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_progress', 'Currently in progress'), ('ready', 'Ready to send'), ('completed', 'Already sent')], default='new', max_length=100, verbose_name='Order status')),
                ('order_type', models.CharField(choices=[('self', 'For own needs'), ('For customers', 'For customers')], default='self', max_length=100, verbose_name='Order type')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Order comment')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date of order creation')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of receipt of the order ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of product')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total cost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('orders', models.ManyToManyField(to='catalogapp.Order', verbose_name="User'selection order")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total cost')),
                ('in_order', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogapp.userclass', verbose_name='Owner')),
                ('products', models.ManyToManyField(blank=True, to='catalogapp.SelectedProduct')),
            ],
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='selected_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.selection', verbose_name='Selected items'),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='catalogapp.userclass', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='order',
            name='selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogapp.selection', verbose_name='Selection'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.userclass', verbose_name='User'),
        ),
    ]
